DECLARE @FIRSTNAME AS NVARCHAR(20)
DECLARE @MIDDLENAME AS NVARCHAR(20)
DECLARE @LASTNAME AS NVARCHAR(20)

SET @FIRSTNAME = 'THABANG'
SET @MIDDLENAME = 'ME'
SET @LASTNAME = 'MOTHAPO'

-- SELECT @FIRSTNAME + ' ' + @MIDDLENAME + ' ' + @LASTNAME
SELECT @FIRSTNAME + ' ' + IIF(@MIDDLENAME IS NULL,'', + ' ' + @LASTNAME
SELECT @FIRSTNAME + ' ' + CASE WHEN (@MIDDLENAME IS NULL,'' ELSE ' ' @MIDDLENAME END + ' ' + @LASTNAME