DECLARE @charASCII AS VARCHAR(10) = ' Hellothere'

DECLARE @charUNICODE AS nVARCHAR(10) = N'hello'

select LEFT(@charASCII,2) AS MYASCII, RIGHT(@charUNICODE,2) AS MYUNICODE
SELECT SUBSTRING(@charASCII,3,2) AS MIDDLELETTERS
SELECT RTRIM(LTRIM(@charASCII)) AS TRIM
SELECT REPLACE(@charASCII, 'l', 'L')as REPLACE
SELECT UPPER(@charASCII) AS UPPER
SELECT LOWER(@charASCII) AS LOWER
