name: Deploy SSIS Package

on:
  push:
    branches:
      - main
    paths:
      - 'SSISProject/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Must be a Windows runner with SSIS tools installed
    environment: production

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup SSIS DevOps Tools
      - name: Setup SSIS DevOps Tools
        uses: jonlabelle/setup-ssis-devops-tools@v1

      # Step 3: Build SSIS Project
      - name: Build SSIS Project
        shell: cmd
        run: |
          SSISBuild.exe ^
            -p:"${{ github.workspace }}\\SSISProject\\MySSISProject.dtproj" ^
            -o:"${{ github.workspace }}\\SSISBuild"

      # Step 4: Deploy SSIS package to SSISDB
      - name: Deploy SSIS Package
        shell: cmd
        run: |
          SSISDeploy.exe ^
            -s:"${{ github.workspace }}\\SSISBuild\\MySSISProject.ispac" ^
            -d:"catalog;/SSISDB/MyFolder/MyProject;MyServerName" ^
            -at:winAuth
