name: Deploy SSIS Package

on:
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug ISPAC path
        shell: powershell
        run: |
          Write-Output "Workspace: $env:GITHUB_WORKSPACE"
          dir "$env:GITHUB_WORKSPACE\HandsOnProjects\Timesheets\bin\Development"

      - name: Deploy ISPAC using SSISDeploy.exe
        shell: cmd
        run: |
          set "ISPAC_PATH=%GITHUB_WORKSPACE%\HandsOnProjects\Timesheets\bin\Development\Timesheets.ispac"
          set "FOLDER=TimesheetsFolder"
          set "PROJECT=Timesheets"
          set "SERVER=localhost"
          
          echo Deploying %ISPAC_PATH% to %SERVER%\SSISDB\%FOLDER%\%PROJECT%
          
          SSISDeploy.exe ^
            -s:"%ISPAC_PATH%" ^
            -d:"catalog;/SSISDB/%FOLDER%/%PROJECT%;%SERVER%" ^
            -at:winAuth ^
            -v:detailed
