name: Deploy SQL Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
    secrets:
      SQL_SERVER_HOST:
        required: true
      SQL_SERVER_PORT:
        required: true
      SQL_USER:
        required: true
      SQL_PASSWORD:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update package list
        run: sudo apt-get update

      - name: Install prerequisites
        run: |
          sudo apt-get install -y curl gnupg

      - name: Add Microsoft repository
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update

      - name: Resolve ODBC package conflicts
        run: |
          sudo apt-get remove -y libodbc2 libodbcinst2 unixodbc-common
          sudo apt-get install -y mssql-tools unixodbc unixodbc-dev

      - name: Deploy database
        run: |
          # Example deployment command using mssql-tools
          /opt/mssql-tools/bin/sqlcmd -S ${{ secrets.SQL_SERVER_HOST }},${{ secrets.SQL_SERVER_PORT }} \
            -U ${{ secrets.SQL_USER }} \
            -P ${{ secrets.SQL_PASSWORD }} \
            -Q "CREATE DATABASE AutoDBThabang"
