name: Deployment Exercise 1

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Change to your Node.js version

      - name: Install Dependencies
        run: npm install  # or use npm ci if package-lock.json exists

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build Code
        run: npm run build

      - name: Deploy Code
        run: |
          echo "Deploying..."
          # Add actual deployment commands here, like:
          # scp -r ./dist user@server:/var/www/app
          # firebase deploy
          # vercel --prod
"
