name: Deploy SQL Template

on:
  workflow_call:
    inputs:
      environment:
        description: 'Target environment (e.g., development, production)'
        required: true
        type: string
      sql_script_path:
        description: 'Path to the SQL script in the repository'
        required: true
        type: string
    secrets:
      SQL_SERVER:
        description: 'SQL Server host and port'
        required: true
      SQL_USER:
        description: 'SQL Server username'
        required: true
      SQL_PASSWORD:
        description: 'SQL Server password'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SQL_SERVER: ${{ secrets.SQL_SERVER }}
      SQL_USER: ${{ secrets.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Microsoft SQL Server Tools (sqlcmd) on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https gnupg
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo "/opt/mssql-tools/bin" >> $GITHUB_PATH

      - name: Verify SQLCMD installation
        run: sqlcmd -?

      - name: Debug print variables
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "SQL_SERVER: $SQL_SERVER"
          echo "SQL_USER: $SQL_USER"
          echo "SQL_PASSWORD: ***"

      - name: Test SQL Server connection
        run: |
          sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASSWORD" -Q "SELECT 1 AS connection_test;" -b -o test_output.log
          cat test_output.log

      - name: Run SQL Script
        run: |
          sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASSWORD" -i ${{ inputs.sql_script_path }} -b -o sql_output.log
          cat sql_output.log

      - name: Verify Database and Table
        run: |
          sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASSWORD" -Q "USE AutoDBThabang; SELECT * FROM [user];" -b -o verify_output.log
          cat verify_output.log
