- name: Clean unused package references
  shell: powershell
  run: |
    $projectFile = "${{ github.workspace }}\HandsOnProject\Timesheets\Integration Services Project1.dtproj"
    [xml]$xml = Get-Content $projectFile
    $pkgFiles = $xml.Project.Packages.PackageFile
    $toRemove = @()

    foreach ($pkg in $pkgFiles) {
      $pkgPath = Join-Path (Split-Path $projectFile) $pkg.InnerText
      if (-not (Test-Path $pkgPath)) {
        Write-Output "Removing missing reference: $($pkg.InnerText)"
        $toRemove += $pkg
      }
    }

    foreach ($pkg in $toRemove) {
      $null = $xml.Project.Packages.RemoveChild($pkg)
    }

    $xml.Save($projectFile)
    Write-Output "Cleaned missing .dtsx references from .dtproj."
