name: Deploy SQL DB and Call SSIS Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-database:
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sqlcmd
        run: |
          choco install sqlcmd --no-progress

      - name: Run SQL script to deploy DB and tables
        run: |
          sqlcmd -S ${{ secrets.SQL_SERVER }} -U ${{ secrets.SQL_USER }} -P ${{ secrets.SQL_PASSWORD }} -i SQL_Script/SQL.sql
        timeout-minutes: 2

  run-sql-jobs:
    needs: deploy-database
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      - name: Run SQL Server Jobs
        shell: pwsh
        run: |
          try {
            Write-Host "Running SQL Server Jobs..."
            .\scripts\run_sql_jobs.ps1
            Write-Host "SQL Jobs completed successfully."
            exit 0
          } catch {
            Write-Error "Error running SQL Jobs: $_"
            exit 1
          }

  call-ssis:
    needs: run-sql-jobs
    uses: ThabangMothapo/timesheet-system/.github/workflows/SSIS.yml@main  # Replace with your repo path
    secrets: inherit
   
