name: Setup SQL Server Database

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy_sql_template.yml
    with:
      environment: development
      sql_script_path: scripts/setup.sql
    secrets:
      SQL_SERVER: ${{ secrets.SQL_SERVER_DEV }}
      SQL_USER: ${{ secrets.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}

  deploy-prod:
    needs: deploy-dev  # Ensures production runs after development
    if: success()      # Only runs if deploy-dev succeeds
    uses: ./.github/workflows/deploy_sql_template.yml
    with:
      environment: production
      sql_script_path: scripts/setup.sql
    secrets:
      SQL_SERVER: ${{ secrets.SQL_SERVER_PROD }}
      SQL_USER: ${{ secrets.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
