name: Main Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy to Development
    uses: ./.github/workflows/deploy-sql-template.yml
    secrets:
      sql_server_host: ${{ secrets.DEV_SQL_SERVER_HOST }}
      sql_server_port: ${{ secrets.DEV_SQL_SERVER_PORT }}
      sql_password: ${{ secrets.DEV_SQL_PASSWORD }}

  deploy-prod:
    name: Deploy to Production
    needs: deploy-dev
    environment: production
    uses: ./.github/workflows/deploy-sql-template.yml
     secrets:
      sql_server_host: ${{ secrets.PROD_SQL_SERVER_HOST }}
      sql_server_port: ${{ secrets.PROD_SQL_SERVER_PORT }}
      sql_password: ${{ secrets.PROD_SQL_PASSWORD }}
