name: Notify Teams on Pull Request

on:
  pull_request:
    types: [opened, closed]

jobs:
  notify-teams:
    runs-on: ubuntu-latest

    steps:
      - name: Send PR Notification to Teams
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
                "text": "🚀 A new Pull Request has been created!\n
                **Title:** ${{ github.event.pull_request.title }}\n
                **By:** ${{ github.actor }}\n
                **URL:** ${{ github.event.pull_request.html_url }}"
              }' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}
